apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-config
  # namespace: calcom
data:
  NODE_ENV: "production"
  API_PORT: "3000"
  LOG_LEVEL: "info"
  API_KEY_PREFIX: "cal_"
  
  NEXT_PUBLIC_WEBAPP_URL: "https://app.yourdomain.com"
  NEXT_PUBLIC_API_V2_URL: "https://api.yourdomain.com"
  
  IS_E2E: "false"
