apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
  # namespace: calcom
  labels:
    app: nodejs-api
spec:
  type: ClusterIP
  selector:
    app: nodejs-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
